"use strict";

parserFactory.register("mydramanovel.com", () => new MydramanovelParser());

class MydramanovelParser extends Parser { // eslint-disable-line no-unused-vars
    constructor() {
        super();
    }

    async getChapterUrls(dom) {
        // block ids (#tdi_NN) are generated by the theme and change, so match chapter links by URL instead
        let novelUrl = dom.baseURI.split(/[?#]/)[0];
        let seen = new Set();
        return [...dom.querySelectorAll(".td-module-thumb a, h3.entry-title a")]
            .filter(a => a.href.startsWith(novelUrl) && a.href !== novelUrl && !seen.has(a.href) && seen.add(a.href))
            .map(a => this.hyperLinkToChapter(a));
    }

    hyperLinkToChapter(link) {
        return {
            sourceUrl: link.href,
            title: link.getAttribute("title") ?? link.textContent.trim()
        };
    }

    findContent(dom) {
        return dom.querySelector("div.td-post-content");
    }

    removeUnwantedElementsFromContentElement(element) {
        util.removeChildElementsMatchingSelector(element, "style");
        super.removeUnwantedElementsFromContentElement(element);
    }

    extractTitleImpl(dom) {
        return dom.querySelector("h1.tdb-title-text");
    }

    findChapterTitle(dom) {
        return dom.querySelector("h1");
    }

    findCoverImageUrl(dom) {
        let span = dom.querySelector(".td-module-thumb a span[data-img-url]");
        return span?.getAttribute("data-img-url") ?? null;
    }

    getInformationEpubItemChildNodes(dom) {
        return [...dom.querySelectorAll("div.tdb_category_description .tdb-block-inner")];
    }
}
